### ISSUE TITLE
Make PLOTS!!!

### ISSUE THREAD

**Issue by bastienboutonnet** [bastienboutonnet/py-nest-thermostat#11]
## TODO:
- [ ] create a command that gets data from the backend database of the controller
- [ ] investigate plotting options (probably something like plotly as it makes up a nice frontend
- [ ] implement plotting methods
